# Generated by Django 2.0.2 on 2018-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_record',
            name='activity_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time_record',
            name='activity_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time_record',
            name='client_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='time_record',
            name='project_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='time_record',
            name='task_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='time_record',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
