# Generated by Django 2.0.2 on 2018-05-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_logger', '0002_auto_20180513_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_record',
            name='clocked_in',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
