# Generated by Django 2.0.2 on 2018-05-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task_logger', '0003_time_record_clocked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_record',
            name='meal_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time_record',
            name='meal_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
