# Generated by Django 2.0.2 on 2018-05-16 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task_logger', '0004_auto_20180516_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_record',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='time_record',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='time_record',
            name='task_name',
        ),
    ]
